CRITICAL - 2025-09-20 20:46:00 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:46:02 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:46:11 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:46:39 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:47:31 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:49:18 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:49:20 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:49:20 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:49:20 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout.php', [], true)
 5 APPPATH\Controllers\Home.php(12): view('layouts/main_layout.php')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:51:29 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:14 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:15 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:15 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:15 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:16 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:30 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('/layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('/layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:31 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('/layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('/layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:52:31 --> ErrorException: Undefined variable $title
[Method: GET, Route: /]
in APPPATH\Views\layouts\main_layout.php on line 6.
 1 APPPATH\Views\layouts\main_layout.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\laragon\\www\\blog\\app\\Views\\layouts\\main_layout.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('/layouts/main_layout', [], true)
 5 APPPATH\Controllers\AuthController.php(9): view('/layouts/main_layout')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:54:03 --> ErrorException: Array to string conversion
[Method: GET, Route: /]
in APPPATH\Controllers\AuthController.php on line 13.
 1 APPPATH\Controllers\AuthController.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\blog\\app\\Controllers\\AuthController.php', 13)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:54:09 --> ErrorException: Array to string conversion
[Method: GET, Route: /]
in APPPATH\Controllers\AuthController.php on line 13.
 1 APPPATH\Controllers\AuthController.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\blog\\app\\Controllers\\AuthController.php', 13)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 20:55:02 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "partial/footer_view.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('partial/footer_view.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('partial/footer_view', [], true)
 3 APPPATH\Controllers\AuthController.php(14): view('partial/footer_view')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:24 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$2fNHyAUvVeENbjrggzeyFOWjxXfJ1m5UZV/AScKBqmFalBonIkikW\', \'2025-09-20 22:01:24\', \'2025-09-20 22:01:24\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$2fNHyAUvVeENbjrggzeyFOWjxXfJ1m5UZV/AScKBqmFalBonIkikW\', \'2025-09-20 22:01:24\', \'2025-09-20 22:01:24\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:24 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$2fNHyAUvVeENbjrggzeyFOWjxXfJ1m5UZV/AScKBqmFalBonIkikW\', \'2025-09-20 22:01:24\', \'2025-09-20 22:01:24\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$2fNHyAUvVeENbjrggzeyFOWjxXfJ1m5UZV/AScKBqmFalBonIkikW\', \'2025-09-20 22:01:24\', \'2025-09-20 22:01:24\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$2fNHyAUvVeENbjrggzeyFOWjxXfJ1m5UZV/AScKBqmFalBonIkikW\', \'2025-09-20 22:01:24\', \'2025-09-20 22:01:24\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:30 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$TEnPVWxbUa.xZ.Vz/6k6def7R/SEwG/d1..NsfCLBF3vGdNqv7Ud6\', \'2025-09-20 22:01:30\', \'2025-09-20 22:01:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$TEnPVWxbUa.xZ.Vz/6k6def7R/SEwG/d1..NsfCLBF3vGdNqv7Ud6\', \'2025-09-20 22:01:30\', \'2025-09-20 22:01:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:30 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$TEnPVWxbUa.xZ.Vz/6k6def7R/SEwG/d1..NsfCLBF3vGdNqv7Ud6\', \'2025-09-20 22:01:30\', \'2025-09-20 22:01:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$TEnPVWxbUa.xZ.Vz/6k6def7R/SEwG/d1..NsfCLBF3vGdNqv7Ud6\', \'2025-09-20 22:01:30\', \'2025-09-20 22:01:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$TEnPVWxbUa.xZ.Vz/6k6def7R/SEwG/d1..NsfCLBF3vGdNqv7Ud6\', \'2025-09-20 22:01:30\', \'2025-09-20 22:01:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:32 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$zZakTltJjwOnrABYmEW/qeWGF1aocwI2.5rjR7dKe1Tg58M1FJCH2\', \'2025-09-20 22:01:32\', \'2025-09-20 22:01:32\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$zZakTltJjwOnrABYmEW/qeWGF1aocwI2.5rjR7dKe1Tg58M1FJCH2\', \'2025-09-20 22:01:32\', \'2025-09-20 22:01:32\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:32 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$zZakTltJjwOnrABYmEW/qeWGF1aocwI2.5rjR7dKe1Tg58M1FJCH2\', \'2025-09-20 22:01:32\', \'2025-09-20 22:01:32\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$zZakTltJjwOnrABYmEW/qeWGF1aocwI2.5rjR7dKe1Tg58M1FJCH2\', \'2025-09-20 22:01:32\', \'2025-09-20 22:01:32\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$zZakTltJjwOnrABYmEW/qeWGF1aocwI2.5rjR7dKe1Tg58M1FJCH2\', \'2025-09-20 22:01:32\', \'2025-09-20 22:01:32\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:36 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$hmjAmqSsozXEyv6siJR1I.a/IfWFTTmkQZ0teABFJ4hI7kWvx/76y\', \'2025-09-20 22:01:36\', \'2025-09-20 22:01:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$hmjAmqSsozXEyv6siJR1I.a/IfWFTTmkQZ0teABFJ4hI7kWvx/76y\', \'2025-09-20 22:01:36\', \'2025-09-20 22:01:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:36 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$hmjAmqSsozXEyv6siJR1I.a/IfWFTTmkQZ0teABFJ4hI7kWvx/76y\', \'2025-09-20 22:01:36\', \'2025-09-20 22:01:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$hmjAmqSsozXEyv6siJR1I.a/IfWFTTmkQZ0teABFJ4hI7kWvx/76y\', \'2025-09-20 22:01:36\', \'2025-09-20 22:01:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$hmjAmqSsozXEyv6siJR1I.a/IfWFTTmkQZ0teABFJ4hI7kWvx/76y\', \'2025-09-20 22:01:36\', \'2025-09-20 22:01:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$mBJYQqFu1ojsx.kF6IqseuoTfi51JQAIXkoIFKfYuVx7pB..dV8P6\', \'2025-09-20 22:01:47\', \'2025-09-20 22:01:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$mBJYQqFu1ojsx.kF6IqseuoTfi51JQAIXkoIFKfYuVx7pB..dV8P6\', \'2025-09-20 22:01:47\', \'2025-09-20 22:01:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:47 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$mBJYQqFu1ojsx.kF6IqseuoTfi51JQAIXkoIFKfYuVx7pB..dV8P6\', \'2025-09-20 22:01:47\', \'2025-09-20 22:01:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$mBJYQqFu1ojsx.kF6IqseuoTfi51JQAIXkoIFKfYuVx7pB..dV8P6\', \'2025-09-20 22:01:47\', \'2025-09-20 22:01:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$mBJYQqFu1ojsx.kF6IqseuoTfi51JQAIXkoIFKfYuVx7pB..dV8P6\', \'2025-09-20 22:01:47\', \'2025-09-20 22:01:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
ERROR - 2025-09-20 22:01:50 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\blog\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\blog\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\blog\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\blog\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\blog\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\blog\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\blog\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\blog\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\blog\app\Controllers\AuthController.php(63): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\blog\system\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
#9 C:\laragon\www\blog\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\laragon\www\blog\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\blog\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\blog\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\blog\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\laragon\www\blog\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-09-20 22:01:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: insertUser]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$UCp4m1VV42lY8dER.TH77O158wr5OLVtpBZLabiIcmDO21sno9RsK\', \'2025-09-20 22:01:50\', \'2025-09-20 22:01:50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$UCp4m1VV42lY8dER.TH77O158wr5OLVtpBZLabiIcmDO21sno9RsK\', \'2025-09-20 22:01:50\', \'2025-09-20 22:01:50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:01:50 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$UCp4m1VV42lY8dER.TH77O158wr5OLVtpBZLabiIcmDO21sno9RsK\', \'2025-09-20 22:01:50\', \'2025-09-20 22:01:50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$UCp4m1VV42lY8dER.TH77O158wr5OLVtpBZLabiIcmDO21sno9RsK\', \'2025-09-20 22:01:50\', \'2025-09-20 22:01:50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Usuario de Prueba\', \'prueba@example.com\', \'$2y$10$UCp4m1VV42lY8dER.TH77O158wr5OLVtpBZLabiIcmDO21sno9RsK\', \'2025-09-20 22:01:50\', \'2025-09-20 22:01:50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthController.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->insertUser()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:36:28 --> ErrorException: Trying to access array offset on false
[Method: POST, Route: store]
in APPPATH\Controllers\AuthController.php on line 36.
 1 APPPATH\Controllers\AuthController.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on false', 'C:\\laragon\\www\\blog\\app\\Controllers\\AuthController.php', 36)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->store()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
CRITICAL - 2025-09-20 22:36:55 --> ErrorException: Trying to access array offset on false
[Method: POST, Route: store]
in APPPATH\Controllers\AuthController.php on line 36.
 1 APPPATH\Controllers\AuthController.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on false', 'C:\\laragon\\www\\blog\\app\\Controllers\\AuthController.php', 36)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->store()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\blog\\public\\index.php')
